version: "2"

services:
  sf-mongo:
    image: mongo:3.6.6
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    command: "mongod --smallfiles"
    
